sudo: required
services:
  -docker
dist: trusty
language: scala
scala:
 - 2.11.12
env:
 - export LD_LIBRARY_PATH=/usr/local/lib
before_install:
 - wget http://apache.crihan.fr/dist/maven/maven-3/3.6.0/binaries/apache-maven-3.6.0-bin.zip
 - unzip -qq apache-maven-3.6.0-bin.zip
 - export M2_HOME=$PWD/apache-maven-3.6.0
 - export PATH=$M2_HOME/bin:$PATH
script:
 - mvn test -pl eclair-core -Dsuites='fr.acinq.eclair.payment.PaymentLifecycleSpec'
cache:
 directories:
  - .autoconf
  - $HOME/.m2
jdk:
 - openjdk11
notifications:
 email:
  - ops@acinq.fr
